permissions: read-all
name: publish-to-twitter
on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: infraway/tweet-action@v1.0.1
        with:
          status: "published #ThreatPot ${{github.ref_name}}! https://github.com/khulnasoft/ThreatPot/releases/tag/${{github.ref_name}} #ThreatIntelligence #CyberSecurity #OpenSource #osint #honeypot #tpot"
          api_key: ${{ secrets.TWITTER_API_KEY }}
          api_key_secret: ${{ secrets.TWITTER_API_KEY_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}